#!/bin/bash

if [ $# -ge 1 ]
then

        dpkg -s $1 &> /dev/null

        if [ $? -eq 0 ]
        then
                echo "The package is already installed!"
        else
                echo "Starting indexes update..."
                sudo apt-get update
                echo "Indexes have been updated. Starting the installation process..."
                sudo apt-get install -y $1
                echo "The package was successfully installed with exit code of $?"
        fi
else
        echo "Please enter a package to install!"
fi
